
/*
PROJECT:GROUP 2_1

AUTHORS AND MATRIC NUMBERS:

ABU SAYED                   59395
ENG YEE WEI                 55882
ISMA KHALIL BIN SEMAN       50542
MELVIN PAUL PETER           52468
NUR AIN BINTI RAMLEE        58932

HONOUR CODE: WE PLEDGE THAT THIS PROGRAM REPRESENTS OUR OWN PROGRAM CODE. 
WE RECEIVED HELP FROM NIELTON DIDI
IN DEVELOPING AND DEBUGGING OUR PROGRAM.
*/

import javax.swing.JOptionPane;


public class Home extends javax.swing.JFrame {
String player1; 
String player2; 
/**
     * Creates new form Home
     */
    public Home() {
        super("Octagonal Chess Game");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnStartGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFPlayer1 = new javax.swing.JTextField();
        JTFPlayer2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnStartGame.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jBtnStartGame.setForeground(new java.awt.Color(0, 0, 255));
        jBtnStartGame.setText("START GAME");
        jBtnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartGameActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giphy.gif"))); // NOI18N
        jLabel1.setText(" ");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("WELCOME TO OCTAGONAL CHESS BATTLE !");

        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chess.gif"))); // NOI18N
        jLabel3.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("ENTER PLAYER'S NAME:");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel5.setText("PLAYER 1 :");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel6.setText("PLAYER 2 :");

        JTFPlayer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTFPlayer1.setText(" ");

        JTFPlayer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTFPlayer2.setText(" ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/water.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnStartGame)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(JTFPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(JTFPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(jBtnStartGame))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jLabel7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartGameActionPerformed
     
        boolean isValidationPassed = inputsValidation();
        
        if(!isValidationPassed)
        {
            // skip this method
            return;
        }
       
      String player1 = JTFPlayer1.getText().trim();
      System.out.println(JTFPlayer1.getText());
      String player2 = JTFPlayer2.getText().trim();
        
      setVisible(false);
      ChessInterface startGame = new ChessInterface(JTFPlayer1.getText(),JTFPlayer2.getText());
      startGame.setVisible(true);
      
       
    }//GEN-LAST:event_jBtnStartGameActionPerformed

     private boolean inputsValidation() 
    {
        String player1 = JTFPlayer1.getText().trim();
        String player2 = JTFPlayer2.getText().trim();
        
        if(player1.isEmpty() && player2.isEmpty()) //check field have input or not
        {
            JOptionPane.showMessageDialog(null, "Please fill in the name of players", "Error Message", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } 
        
        else if(player1 == null || player1.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill in the name of player 1", "Error Message", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } 
        
        else if(player2 == null || player2.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill in the name of player 2", "Error Message", JOptionPane.INFORMATION_MESSAGE);
            return false;
        } 

        // Pass through all the validations
        return true;
    }
     
     public String getname1()
     {
         System.out.println(JTFPlayer1.getText());
         return player1;
     }
     
     public String getname2()
     {
         System.out.println(JTFPlayer2.getText());
         return player2;
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFPlayer1;
    private javax.swing.JTextField JTFPlayer2;
    private javax.swing.JButton jBtnStartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
